'use client';
import { useState,useEffect,useRef } from 'react';
import { Search,MapPin,Heart,BedDouble,Utensils,LayoutGrid,ClipboardList,Store,Settings,Plus,X,Check,WifiOff,Download,LogOut,Star,SlidersHorizontal,ShieldCheck,LoaderCircle,CheckCircle2 } from 'lucide-react';
import type { Listing,State,Booking } from '../lib/domain';
import { money,quote,today } from '../lib/domain';
import { readDemoState,mutateDemoState } from '../lib/demo-store';
type View='explore'|'saved'|'requests'|'provider'|'admin';
const empty:State={profile:null,listings:[],favorites:[],requests:[],reviews:[],feeBps:500};
const unit=(l:{category:string})=>l.category==='Hospedaje'?' / 30 días':' / comida';
type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function Marketplace({signedIn,demoMode=false,basePath='/'}:{signedIn:boolean;demoMode?:boolean;basePath?:string}){
 const image=(l:{category:string})=>basePath+(l.category==='Hospedaje'?'habitacion.png':'almuerzo.png');
 const [data,setData]=useState<State>(empty),[loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[offline,setOffline]=useState(false);
 const [view,setView]=useState<View>('explore'),[category,setCategory]=useState('Hospedaje'),[search,setSearch]=useState(''),[zone,setZone]=useState('Todas las zonas'),[max,setMax]=useState(''),[sort,setSort]=useState('recommended');
 const [detail,setDetail]=useState<Listing|null>(null),[editor,setEditor]=useState<Partial<Listing>|null>(null),[review,setReview]=useState<Booking|null>(null),[profileOpen,setProfileOpen]=useState(false),[install,setInstall]=useState<InstallEvent|null>(null),[installHelp,setInstallHelp]=useState(false);
 const [qty,setQty]=useState(1),[date,setDate]=useState(today()),[note,setNote]=useState(''),[requestKey,setRequestKey]=useState('');
 const [profileName,setProfileName]=useState(''),[profileRole,setProfileRole]=useState('Estudiante'),[consent,setConsent]=useState(false),[rating,setRating]=useState(5),[comment,setComment]=useState(''); const firstView=useRef(true);
 const cache=(s:State)=>{if(demoMode)return;if('serviceWorker'in navigator)navigator.serviceWorker.ready.then(reg=>reg.active?.postMessage({type:'CATALOG',listings:s.listings.filter(l=>l.active).map(({id,title,category,provider,zone,description,features,price,active,available,demo})=>({id,title,category,provider,zone,description,features,price,active,available,demo})),feeBps:s.feeBps}));};
 async function load(){setLoading(true);setError('');try{if(demoMode){const s=readDemoState();setData(s);if(firstView.current&&s.profile?.role==='Prestador')setView('provider');firstView.current=false;return;}const r=await fetch('/api/state',{cache:'no-store'}),s=await r.json() as State & {error?:string};if(!r.ok)throw Error(s.error||'No pudimos completar la operación.');setData(s);cache(s);if(detail)setDetail(s.listings.find(l=>l.id===detail.id)||null);if(firstView.current&&s.profile?.role==='Prestador')setView('provider');firstView.current=false;}catch(e){if(!navigator.onLine){try{const r=await fetch('/offline-catalog.json');if(r.ok){setData({...empty,...await r.json()});setNotice('Catálogo guardado: consulta sin conexión.');}}catch{}}setError(e instanceof Error?e.message:'No pudimos cargar la información.');}finally{setLoading(false);}}
 useEffect(()=>{setOffline(!navigator.onLine);const on=()=>{setOffline(false);if(signedIn)load();},off=()=>setOffline(true),prompt=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',prompt);if('serviceWorker'in navigator)navigator.serviceWorker.register(basePath+'sw.js',{scope:basePath}).catch(()=>{});if(signedIn)load();return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',prompt);};},[signedIn,demoMode,basePath]);
 useEffect(()=>{if(data.profile){setProfileName(data.profile.name);setProfileRole(data.profile.role);setConsent(true);}},[data.profile]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{if(!(detail||editor||review||profileOpen||installHelp))return;const before=document.activeElement as HTMLElement,dialog=document.querySelector<HTMLDialogElement>('dialog');dialog?.showModal();const cancel=()=>{setDetail(null);setEditor(null);setReview(null);setProfileOpen(false);setInstallHelp(false);};dialog?.addEventListener('cancel',cancel);return()=>{dialog?.removeEventListener('cancel',cancel);dialog?.close();before?.focus();};},[detail,editor,review,profileOpen,installHelp]);
 async function mutate(body:Record<string,unknown>,message:string){if(offline&&!demoMode){setError('Conéctate a internet para guardar los cambios.');return false;}setBusy(true);setError('');try{if(demoMode){const s=mutateDemoState(body);setData(s);setNotice(message);return true;}const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),s=await r.json() as State & {error?:string};if(!r.ok){if(r.status===409)await load();throw Error(s.error||'No pudimos completar la operación.');}setData(s);cache(s);setNotice(message);return true;}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar.');return false;}finally{setBusy(false);}}
 const ensureProfile=()=>{if(!signedIn)return false;if(!data.profile){setDetail(null);setProfileOpen(true);return false;}return true;};
 const openDetail=(l:Listing)=>{setQty(1);setDate(today());setNote('');setRequestKey(crypto.randomUUID());setDetail(l);};
 const switchView=(v:View)=>{setView(v);setError('');};
 let results=data.listings.filter(l=>l.active&&l.category===category&&(view!=='saved'||data.favorites.includes(l.id))&&(!search||`${l.title} ${l.provider} ${l.features}`.toLowerCase().includes(search.toLowerCase()))&&(zone==='Todas las zonas'||l.zone===zone)&&(!max||l.price<=Number(max)));
 results=[...results].sort(sort==='price'?(a,b)=>a.price-b.price:(a,b)=>b.available-a.available);
 const nav=[{id:'explore',label:'Explorar',icon:LayoutGrid},{id:'saved',label:'Guardados',icon:Heart},{id:'requests',label:'Mis solicitudes',icon:ClipboardList},{id:'provider',label:'Panel del prestador',icon:Store},{id:'admin',label:'Administración',icon:Settings}] as const;
 const q=detail?quote(detail.price,qty,data.feeBps):null;
 const close=()=>{setDetail(null);setEditor(null);setReview(null);setProfileOpen(false);setInstallHelp(false);setError('');};
 const pending=data.requests.filter(r=>r.status==='Pendiente').length;
 const status=(r:Booking,value:string)=>mutate({action:'request-status',id:r.id,status:value},`Solicitud ${value.toLowerCase()}.`);
 return <div className="app-shell">
 <aside className="sidebar"><a className="brand" href={basePath} aria-label="Inicio SIBATE-Conecta"><span className="brand-icon"><MapPin size={24}/></span><span>SIBATÉ<span className="brand-sub">Conecta</span></span></a><div className="location"><MapPin size={14}/> Sibaté, Cundinamarca</div><nav aria-label="Navegación principal">{nav.map(n=><button key={n.id} className={view===n.id?'nav-item selected':'nav-item'} onClick={()=>switchView(n.id)}><n.icon size={19}/><span>{n.label}</span>{n.id==='requests'&&pending>0&&<span className="nav-count">{pending}</span>}</button>)}</nav><div className="pilot-card"><ShieldCheck size={22}/><strong>Tu espacio de prueba</strong><p>Recorre los tres perfiles y valida el servicio con datos de ejemplo.</p><span>{demoMode?'Demostración · MVP 1.0':'Piloto privado · MVP 1.0'}</span></div><div className="sidebar-footer"><small>Iniciativa privada independiente</small><small>Sin vinculación institucional con la ESJIM.</small></div></aside>
 <div className="main-shell"><header className="topbar"><span className="top-context">Servicios locales <span>/</span> {view==='provider'?'Prestador':view==='admin'?'Administración':'Estudiante'}</span><div className="top-actions"><span className="pilot-badge">{demoMode?'Demostración':'Piloto privado'}</span><button className="install-btn" onClick={async()=>{if(install){await install.prompt();setInstall(null);}else setInstallHelp(true);}}><Download size={16}/><span>Instalar app</span></button>{signedIn?<button className="avatar" aria-label="Abrir mi perfil" onClick={()=>setProfileOpen(true)}>{data.profile?.name?.slice(0,1).toUpperCase()||'SC'}</button>:<a className="primary small" href="/signin-with-chatgpt?return_to=%2F" target="_top">Iniciar sesión</a>}</div></header>
 <main id="main"><div className="mobile-brand"><MapPin size={22}/><strong>SIBATÉ Conecta</strong></div>
 {demoMode&&<div className="demo-banner"><strong>Modo demostración</strong><span>Datos de prueba guardados solo en este navegador. Las solicitudes no se envían a prestadores reales.</span></div>}
 {offline&&<div className="banner"><WifiOff size={18}/>{demoMode?'Sin conexión. Puedes probar el recorrido con los datos de este dispositivo.':'Sin conexión. Consulta el catálogo guardado; las solicitudes necesitan internet.'}</div>}
 {error&&<div className="error" role="alert">{error}<button onClick={()=>{setError('');if(!data.listings.length&&signedIn)load();}}>{data.listings.length?'Cerrar':'Reintentar'}</button></div>}
 {!signedIn&&<div className="welcome"><ShieldCheck/><div><strong>Abre tu piloto privado</strong><p>Inicia sesión con ChatGPT para guardar tu perfil, ofertas y solicitudes.</p></div><a className="primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Iniciar sesión</a></div>}
 {signedIn&&!loading&&!data.profile&&(!offline||demoMode)&&<div className="welcome"><div><strong>Comienza con tu perfil</strong><p>Elige estudiante o prestador para probar el recorrido.</p></div><button className="primary" onClick={()=>setProfileOpen(true)}>Crear mi perfil</button></div>}
 {(view==='explore'||view==='saved')&&<><div className="page-heading"><div className="eyebrow">CERCA DE TI, EN SIBATÉ</div><h1>{view==='saved'?'Tus lugares guardados':'Encuentra tu lugar.'}</h1><p>{view==='saved'?'Vuelve a las opciones que te interesan.':'Hospedaje y alimentación para tu etapa de estudio.'}</p></div><div className="catalog-toolbar"><div className="category-tabs" role="group" aria-label="Categoría">{['Hospedaje','Alimentación'].map(c=><button aria-pressed={category===c} className={category===c?'active':''} key={c} onClick={()=>{setCategory(c);setMax('');}}>{c==='Hospedaje'?<BedDouble size={20}/>:<Utensils size={20}/>} {c}</button>)}</div><label className="search"><Search size={19}/><input aria-label="Buscar servicios" placeholder="Busca un servicio o característica" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Limpiar búsqueda" onClick={()=>setSearch('')}><X size={16}/></button>}</label></div><div className="filter-row"><SlidersHorizontal size={18}/><label><span className="sr-only">Zona</span><select value={zone} onChange={e=>setZone(e.target.value)}><option>Todas las zonas</option><option>Zona urbana</option><option>Zona rural</option></select></label><label className="max-price"><span>Hasta</span><input type="number" min="1000" step="1000" aria-label="Precio máximo en COP" placeholder="Precio en COP" value={max} onChange={e=>setMax(e.target.value)}/></label><label className="sort"><span className="sr-only">Ordenar</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Disponibles primero</option><option value="price">Menor precio</option></select></label></div><div className="result-meta"><strong>{results.length} {results.length===1?'opción':'opciones'}</strong><span>Ofertas e imágenes de ejemplo · precios en COP</span></div>
 {loading?<div className="empty"><LoaderCircle className="spin"/><h2>Cargando tus opciones…</h2></div>:results.length?<div className="listing-grid">{results.map(l=><article className="listing-card" key={l.id}><div className="card-image"><img src={image(l)} alt={l.category==='Hospedaje'?'Imagen ilustrativa de una habitación estudiantil':'Imagen ilustrativa de un almuerzo casero'} loading="lazy"/><span className="image-label">Imagen ilustrativa</span><button className={data.favorites.includes(l.id)?'favorite saved':'favorite'} aria-label={data.favorites.includes(l.id)?`Quitar ${l.title} de guardados`:`Guardar ${l.title}`} disabled={busy||(offline&&!demoMode)} onClick={()=>{if(ensureProfile())mutate({action:'favorite',id:l.id,saved:!data.favorites.includes(l.id)},data.favorites.includes(l.id)?'Quitado de guardados.':'Servicio guardado.');}}><Heart size={20} fill={data.favorites.includes(l.id)?'currentColor':'none'}/></button></div><div className="card-body"><div className="card-place"><MapPin size={14}/>{l.zone}<span className={l.available?'availability':'unavailable'}>{l.available?'Disponible':'Sin cupo'}</span></div><h2><button onClick={()=>openDetail(l)}>{l.title}</button></h2><p className="provider-name">{l.provider}</p><div className="features">{l.features.split(',').filter(Boolean).slice(0,3).map(f=><span key={f}>{f}</span>)}</div><div className="card-bottom"><div><strong>{money(l.price)}</strong><span>{unit(l)}</span></div><button className="outline small" onClick={()=>openDetail(l)}>Ver detalle</button></div></div></article>)}</div>:<div className="empty"><Search size={32}/><h2>{view==='saved'?'Todavía no tienes opciones guardadas':'No encontramos opciones'}</h2><p>{view==='saved'?'Usa el corazón de una oferta para guardarla.':'Prueba otra categoría o ajusta los filtros.'}</p><button className="outline" onClick={()=>{setSearch('');setZone('Todas las zonas');setMax('');if(view==='saved')switchView('explore');}}>Explorar opciones</button></div>}
 <div className="service-note"><ShieldCheck size={23}/><div><strong>Decide con toda la información</strong><p>Revisa el precio y la tarifa antes de solicitar. El prestador debe aceptar tu solicitud.</p></div><span>Tarifa de prueba: {data.feeBps/100} %</span></div></>}
 {(view==='requests'||view==='provider')&&<><div className="page-heading split"><div><div className="eyebrow">{view==='provider'?'TU OFERTA LOCAL':'TU ACTIVIDAD'}</div><h1>{view==='provider'?'Panel del prestador':'Mis solicitudes'}</h1><p>{view==='provider'?'Publica tus servicios y responde a las solicitudes del piloto.':'Consulta el estado de cada servicio que solicitaste.'}</p></div>{view==='provider'&&<button className="primary" disabled={offline&&!demoMode} onClick={()=>{if(ensureProfile())setEditor({category:'Hospedaje',zone:'Zona urbana',available:1,provider:data.profile?.name||''});}}><Plus size={18}/> Nueva publicación</button>}</div>
 {view==='provider'&&<><div className="metrics"><div><span>Publicaciones activas</span><strong>{data.listings.filter(l=>l.active).length}</strong></div><div><span>Solicitudes pendientes</span><strong>{pending}</strong></div><div><span>Servicios completados</span><strong>{data.requests.filter(r=>r.status==='Completada').length}</strong></div></div><section className="panel"><h2>Mis publicaciones</h2><div className="publication-list">{data.listings.map(l=><div className="publication" key={l.id}><img src={image(l)} alt="Imagen ilustrativa"/><div><strong>{l.title}</strong><span>{l.category} · {money(l.price)}{unit(l)}</span><small>{l.active?'Activa':'Pausada'} · {l.available?'Disponible':'Sin cupo'}</small></div><button className="outline small" disabled={busy||(offline&&!demoMode)} onClick={()=>setEditor(l)}>Editar</button><button className="text-btn" disabled={busy||(offline&&!demoMode)} onClick={()=>mutate({action:'listing-status',id:l.id,active:!l.active},l.active?'Publicación pausada.':'Publicación activada.')}>{l.active?'Pausar':'Activar'}</button></div>)}</div></section></>}
 <section className="panel"><div className="section-title"><h2>{view==='provider'?'Solicitudes recibidas':'Historial de solicitudes'}</h2><span className="chip">{data.requests.length}</span></div>{!data.requests.length?<div className="empty compact"><ClipboardList size={28}/><h3>Aún no hay solicitudes</h3><p>Solicita una opción desde Explorar para probar el recorrido completo.</p><button className="outline" onClick={()=>switchView('explore')}>Explorar servicios</button></div>:<div className="requests-list">{data.requests.map(r=><article className="request-card" key={r.id}><div className="request-top"><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span><small>SC-{r.id.slice(0,8).toUpperCase()}</small></div><h3>{r.title}</h3><p>{r.provider}</p><div className="request-details"><span>Fecha: {r.date.split('-').reverse().join('/')}</span><span>{r.quantity} {r.category==='Hospedaje'?'periodo de 30 días':'comida(s)'}</span><strong>Total: {money(r.total)}</strong></div><small>Servicio: {money(r.base)} · Tarifa ({r.fee_bps/100} %): {money(r.fee)}</small>{r.note&&<p className="request-note">{r.note}</p>}<div className="request-actions">{view==='provider'&&r.status==='Pendiente'&&<><button className="primary small" disabled={busy||(offline&&!demoMode)} onClick={()=>status(r,'Aceptada')}>Aceptar</button><button className="outline small" disabled={busy||(offline&&!demoMode)} onClick={()=>status(r,'Rechazada')}>Rechazar</button></>}{view==='provider'&&r.status==='Aceptada'&&<button className="primary small" disabled={busy||(offline&&!demoMode)} onClick={()=>status(r,'Completada')}>Marcar completada</button>}{view==='requests'&&['Pendiente','Aceptada'].includes(r.status)&&<button className="outline small" disabled={busy||(offline&&!demoMode)} onClick={()=>status(r,'Cancelada')}>Cancelar solicitud</button>}{view==='requests'&&r.status==='Completada'&&<button className="outline small" disabled={offline&&!demoMode} onClick={()=>{const existing=data.reviews.find(v=>v.request_id===r.id);setRating(existing?.rating||5);setComment(existing?.comment||'');setReview(r);}}><Star size={15}/>{data.reviews.some(v=>v.request_id===r.id)?'Editar valoración':'Valorar servicio'}</button>}{view==='requests'&&r.status==='Pendiente'&&<span>Esperando respuesta del prestador</span>}</div>{data.reviews.find(v=>v.request_id===r.id)&&<div className="review-display"><Star size={14}/>{data.reviews.find(v=>v.request_id===r.id)?.rating}/5 · {data.reviews.find(v=>v.request_id===r.id)?.comment}</div>}</article>)}</div>}</section></>}
 {view==='admin'&&<><div className="page-heading"><div className="eyebrow">VALIDACIÓN DEL PILOTO</div><h1>Administración</h1><p>Revisa la actividad y ajusta la tarifa de tu espacio privado.</p></div><div className="metrics"><div><span>Solicitudes totales</span><strong>{data.requests.length}</strong></div><div><span>Valor solicitado</span><strong>{money(data.requests.filter(r=>!['Cancelada','Rechazada'].includes(r.status)).reduce((s,r)=>s+r.base,0))}</strong></div><div><span>Tarifas estimadas</span><strong>{money(data.requests.filter(r=>r.status==='Completada').reduce((s,r)=>s+r.fee,0))}</strong><small>Sobre servicios completados; sin cobros</small></div></div><div className="admin-grid"><section className="panel"><h2>Tarifa de servicio</h2><p>Se aplica al estudiante. El prestador recibe el precio base completo en la simulación.</p><form onSubmit={async e=>{e.preventDefault();if(!ensureProfile())return;const f=new FormData(e.currentTarget);await mutate({action:'fee',bps:Math.round(Number(f.get('fee'))*100)},'Tarifa actualizada para las próximas solicitudes.');}}><label>Porcentaje de prueba<input name="fee" type="number" min="0" max="20" step="0.1" defaultValue={data.feeBps/100} key={data.feeBps} required/></label><button className="primary" disabled={busy||(offline&&!demoMode)}>Guardar tarifa</button></form><small>Supuesto del piloto, pendiente de validación. Las solicitudes existentes conservan su tarifa.</small></section><section className="panel"><h2>Perfil del piloto</h2><p><strong>{data.profile?.name||'Perfil pendiente'}</strong></p><p>{data.profile?.role||'Completa tu perfil para comenzar.'}</p><button className="outline" onClick={()=>setProfileOpen(true)}>Editar perfil</button><div className="info-box">Las vistas Estudiante, Prestador y Administración usan tus mismos datos de prueba. No conectan cuentas de personas distintas.</div></section></div><section className="panel"><h2>Operaciones del piloto</h2>{data.requests.length?<div className="table-wrap"><table><thead><tr><th>Referencia</th><th>Servicio</th><th>Estado</th><th>Tarifa</th><th>Total</th></tr></thead><tbody>{data.requests.map(r=><tr key={r.id}><td>SC-{r.id.slice(0,8)}</td><td>{r.title}</td><td>{r.status}</td><td>{money(r.fee)}</td><td>{money(r.total)}</td></tr>)}</tbody></table></div>:<p>Aún no hay operaciones registradas.</p>}</section></>}
 <footer className="main-footer"><span>SIBATÉ Conecta · Piloto privado</span><span>Ofertas de prueba · Sin pagos reales</span></footer></main></div>
 <nav className="mobile-nav" aria-label="Navegación móvil">{nav.map(n=><button key={n.id} aria-label={n.label} aria-current={view===n.id?'page':undefined} className={view===n.id?'active':''} onClick={()=>switchView(n.id)}><n.icon size={21}/><span>{n.id==='provider'?'Prestador':n.id==='admin'?'Admin':n.id==='requests'?'Solicitudes':n.label}</span></button>)}</nav>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}
 {(detail||editor||review||profileOpen||installHelp)&&<dialog className="modal" aria-labelledby="dialog-title"><button className="close-modal" aria-label="Cerrar ventana" disabled={busy} onClick={close}><X size={21}/></button>{error&&<div className="error" role="alert">{error}</div>}
 {detail&&q&&<><img className="detail-image" src={image(detail)} alt="Imagen ilustrativa del servicio"/><div className="modal-content"><div className="eyebrow">{detail.category.toUpperCase()} · OFERTA DE PRUEBA</div><h2 id="dialog-title">{detail.title}</h2><p className="muted"><MapPin size={15}/> {detail.zone} · {detail.provider}</p><p>{detail.description}</p><div className="features detail-features">{detail.features.split(',').filter(Boolean).map(f=><span key={f}><Check size={14}/>{f}</span>)}</div>{data.reviews.filter(r=>r.listing_id===detail.id).map((r,i)=><div className="review-display" key={i}><Star size={16}/>{r.rating}/5 · {r.comment}</div>)}<form onSubmit={async e=>{e.preventDefault();if(!ensureProfile())return;if(await mutate({action:'request',id:detail.id,quantity:qty,date,note,key:requestKey,expectedTotal:q.total},'Solicitud creada. Puedes verla en Mis solicitudes.')){close();setView('requests');}}}><div className="form-row"><label>{detail.category==='Hospedaje'?'Fecha de inicio':'Fecha de recogida'}<input type="date" min={today()} required value={date} onChange={e=>setDate(e.target.value)}/></label>{detail.category==='Alimentación'?<label>Cantidad de comidas<input type="number" min="1" max="30" required value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>:<div className="period"><span>Duración del piloto</span><strong>1 periodo de 30 días</strong></div>}</div><label>Mensaje para el prestador <span className="optional">(opcional)</span><textarea maxLength={800} value={note} onChange={e=>setNote(e.target.value)} placeholder="Cuéntale lo que necesitas. Evita datos sensibles."/></label><div className="quote"><div><span>Precio del servicio</span><strong>{money(q.base)}</strong></div><div><span>Tarifa de prueba ({data.feeBps/100} %)</span><strong>{money(q.fee)}</strong></div><div className="quote-total"><span>Total estimado</span><strong>{money(q.total)}</strong></div></div><p className="fine-print">Esta solicitud es una prueba. No se cobra dinero ni se garantiza una reserva. El prestador debe confirmar disponibilidad.</p><button className="primary full" disabled={busy||(offline&&!demoMode)||!detail.available||!signedIn}>{busy?<LoaderCircle className="spin" size={18}/>:<ClipboardList size={18}/>} {!detail.available?'Sin disponibilidad':'Confirmar solicitud de prueba'}</button>{!data.profile&&signedIn&&<p className="fine-print">Completa tu perfil antes de solicitar.</p>}</form></div></>}
 {editor&&<div className="modal-content"><div className="eyebrow">PANEL DEL PRESTADOR</div><h2 id="dialog-title">{editor.id?'Editar publicación':'Nueva publicación'}</h2><p className="muted">{demoMode?'Publicación de prueba guardada en este navegador.':'Publicación de prueba en tu catálogo privado.'}</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'listing',id:editor.id,...Object.fromEntries(f),available:f.get('available')==='on',price:Number(f.get('price'))},'Publicación guardada.'))close();}}><label>Nombre del servicio<input name="title" defaultValue={editor.title||''} minLength={5} maxLength={100} required placeholder="Ej. Habitación individual con escritorio"/></label><div className="form-row"><label>Categoría<select name="category" defaultValue={editor.category}><option>Hospedaje</option><option>Alimentación</option></select></label><label>Zona<select name="zone" defaultValue={editor.zone}><option>Zona urbana</option><option>Zona rural</option></select></label></div><label>Nombre del prestador<input name="provider" defaultValue={editor.provider||''} minLength={2} maxLength={100} required/></label><label>Precio en COP<input type="number" name="price" defaultValue={editor.price||''} min="1000" max="10000000" step="1" required/><small>Hospedaje por 30 días; alimentación por comida.</small></label><label>Descripción<textarea name="description" defaultValue={editor.description||''} minLength={15} maxLength={1200} required placeholder="Describe el servicio y sus condiciones."/></label><label>Características, separadas por comas<input name="features" defaultValue={editor.features||''} maxLength={300} placeholder="Wi-Fi, Baño privado, Servicios incluidos"/></label><label className="check-label"><input name="available" type="checkbox" defaultChecked={Boolean(editor.available)}/> Hay disponibilidad</label><div className="info-box">La fotografía del piloto es ilustrativa. La carga de fotos reales se incorporará al preparar el piloto con prestadores.</div><button className="primary full" disabled={busy||(offline&&!demoMode)}>{busy?'Guardando…':'Guardar publicación'}</button></form></div>}
 {review&&<div className="modal-content"><h2 id="dialog-title">Valora tu experiencia</h2><p>{review.title}</p><form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'review',id:review.id,rating,comment},'Valoración guardada.'))close();}}><label>Calificación<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(v=><option key={v} value={v}>{v} de 5 estrellas</option>)}</select></label><label>Comentario<textarea required minLength={5} maxLength={600} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="primary full" disabled={busy||(offline&&!demoMode)}>Guardar valoración</button></form></div>}
 {profileOpen&&<div className="modal-content"><div className="eyebrow">TU PERFIL</div><h2 id="dialog-title">Conectemos contigo</h2><p>Elige tu perfil inicial. En este piloto puedes recorrer todas las vistas.</p><form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'profile',name:profileName,role:profileRole,consent},'Perfil guardado.')){close();setView(profileRole==='Prestador'?'provider':'explore');}}}><label>Nombre para mostrar<input required minLength={2} maxLength={80} value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="Tu nombre"/></label><label>Quiero probar como<select value={profileRole} onChange={e=>setProfileRole(e.target.value)}><option>Estudiante</option><option>Prestador</option></select></label><div className="info-box">{demoMode?'Esta demostración guarda tu nombre de prueba, perfil, ofertas y solicitudes solo en este navegador. No tiene cuentas reales ni base de datos compartida.':'Guardamos tu nombre, perfil, publicaciones, solicitudes y valoraciones para operar este piloto privado. Usa datos de prueba y evita documentos de identidad o información institucional.'}</div><label className="check-label"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Autorizo guardar estos datos para probar SIBATÉ Conecta.</label><button className="primary full" disabled={busy||(offline&&!demoMode)||!signedIn}>{busy?'Guardando…':'Guardar mi perfil'}</button></form>{!demoMode&&<a className="signout" onClick={()=>navigator.serviceWorker?.controller?.postMessage({type:'CLEAR_CATALOG'})} href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/> Cerrar sesión</a>}</div>}
 {installHelp&&<div className="modal-content"><Download size={32}/><h2 id="dialog-title">SIBATÉ Conecta en tu dispositivo</h2><p>En Chrome o Edge, abre el menú del navegador y elige «Instalar aplicación» o «Añadir a pantalla de inicio».</p><p>En iPhone, abre la app en Safari, toca Compartir y elige «Añadir a pantalla de inicio».</p><div className="info-box">{demoMode?'Después de abrir la demostración con internet, puedes probar el recorrido sin conexión con los datos guardados en este dispositivo.':'Después de abrir la app con internet, el catálogo queda disponible para consulta sin conexión. Para enviar o responder solicitudes necesitas conectarte.'}</div><button className="primary full" onClick={close}>Entendido</button></div>}
 </dialog>}
 </div>;
}
